package cargo:wasi;

interface http {
    enum method {
        get,
        post,
        put,
        delete,
        head,
        patch
    }

    record request {
        method: method,
        url: string,
        headers: list<tuple<string, string>>,
        body: option<list<u8>>,
    }

    record response {
        status: u16,
        headers: list<tuple<string, string>>,
        body: list<u8>,
    }

    fetch: func(req: request) -> result<response, string>;
}

interface git {
    record checkout-options {
        force: bool,
    }

    clone: func(url: string, dest: string, options: option<checkout-options>) -> result<_, string>;
    fetch: func(repo-path: string) -> result<_, string>;
    ls-remote: func(url: string) -> result<list<tuple<string, string>>, string>;
}

world cargo-bridge {
    import http;
    import git;
}
