[package]
name = "capture_io"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
rand.workspace = true
libc.workspace = true

[lib]
path = "lib.rs"

[lints]
workspace = true
